load("//bazel:rust.bzl", "rust")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust.binary(
    name = "mdcstpp",
    srcs = ["src/main.rs"],
    deps = [
        "@crates//:clap",
        "@crates//:tree-sitter",
        "@crates//:tree-sitter-md",
    ],
)
