load("@rules_rust//rust:defs.bzl", "rust_binary")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust_binary(
    name = "mdcstpp",
    srcs = ["src/main.rs"],
    deps = [
        "@crates//:clap",
        "@crates//:tree-sitter",
        "@crates//:tree-sitter-md",
    ],
)
