load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_rust//rust:defs.bzl", "rust_library")

cc_binary(
    name = "orphan",
    srcs = ["orphan.c"],
)

rust_library(
    name = "subreaper_test",
    testonly = True,
    srcs = ["src/lib.rs"],
    data = [":orphan"],
    visibility = ["//visibility:public"],
    deps = [
        "//syx/testing",
    ],
)
