version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      cargo-dependencies:
        update-types:
          - "minor"
          - "patch"

  # Dependabot has announced support for uv,
  # but there are some use cases that are not yet working.
  # See https://github.com/astral-sh/uv/issues/2512.
  # - package-ecosystem: "uv"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
