---
default_install_hook_types:
  - pre-commit
  - pre-push
fail_fast: false

repos:
  - repo: builtin
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch
          - main
      - id: trailing-whitespace
      - id: end-of-file-fixer
