- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Check if namespace exists
      register: netns_list
      changed_when: false
      ansible.builtin.command:
        cmd: ip netns list

    - name: Stop and disable services
      failed_when: false
      ansible.builtin.systemd:
        name: "{{ item }}@{{ node_name }}.service"
        enabled: false
        state: stopped
      loop:
        - syxvm
        - syxgw

    - name: Remove host route for node fdfc prefix
      failed_when: false
      changed_when: false
      ansible.builtin.command:
        cmd: ip -6 route del {{ fc_ipv6_prefix }}/32 dev {{ bridge_name }}

    - name: Remove host veth
      failed_when: false
      changed_when: false
      ansible.builtin.command:
        cmd: ip link del veth-{{ node_name }}

    - name: Remove network namespace
      when: node_name in (netns_list.stdout_lines | map('split') | map('first') | list)
      ansible.builtin.command:
        cmd: ip netns del {{ node_name }}
