load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "logger",
    srcs = [
        "src/committer.rs",
        "src/file_id.rs",
        "src/lib.rs",
        "src/segment.rs",
        "src/tests.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:bytes",
        "@crates//:crossbeam-skiplist",
        "@crates//:memmap2",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "logger_test",
    size = "small",
    crate = ":logger",
    deps = [
        "//syx/testing",
    ],
)
