load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test", "rust_test_suite")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust_library(
    name = "shtok",
    srcs = ["src/lib.rs"],
    deps = ["@crates//:itertools"],
)

rust_binary(
    name = "shtok_bin",
    srcs = ["src/main.rs"],
    deps = [":shtok"],
)

rust_test(
    name = "shtok_test",
    size = "small",
    crate = ":shtok",
)

rust_test_suite(
    name = "shtok_test_suite",
    size = "small",
    srcs = ["tests/tests.rs"],
    deps = [":shtok"],
)
