load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test", "rust_test_suite")
load("//bazel:pyo3_extension.bzl", "pyo3_extension")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust_library(
    name = "plying",
    srcs = [
        "src/beginning.rs",
        "src/completing.rs",
        "src/filter.rs",
        "src/fuse.rs",
        "src/lib.rs",
        "src/map.rs",
        "src/par.rs",
        "src/seq.rs",
        "src/take.rs",
        "src/xf/comp.rs",
        "src/xf/filter.rs",
        "src/xf/identity.rs",
        "src/xf/map.rs",
        "src/xf/mod.rs",
        "src/xf/take.rs",
        "src/zip.rs",
    ],
)

rust_test(
    name = "plying_test",
    size = "small",
    crate = ":plying",
)

rust_test_suite(
    name = "plying_test_suite",
    size = "small",
    srcs = [
        "tests/simple.rs",
        "tests/thread.rs",
    ],
    shared_srcs = ["tests/helper/mod.rs"],
    deps = [":plying"],
)

py_library(
    name = "plying_py",
    srcs = ["__init__.py"],
    deps = [":_plying"],
)

pyo3_extension(
    name = "_plying",
    srcs = ["_plying.rs"],
    deps = [":plying"],
)

py_test(
    name = "_plying_test",
    size = "small",
    srcs = ["_plying_test.py"],
    deps = [":_plying"],
)
