load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")

pkg_install(
    name = "boot_assets_install",
    srcs = [":boot_assets"],
)

pkg_filegroup(
    name = "boot_assets",
    srcs = [
        ":private_key",
        ":public_key",
        "//boot",
    ],
)

pkg_files(
    name = "public_key",
    srcs = ["testkey.pub"],
    prefix = "key",
)

pkg_files(
    name = "private_key",
    srcs = ["testkey"],
    attributes = pkg_attributes(
        mode = "0600",
    ),
    prefix = "key",
)
