load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust_library(
    name = "unionfind",
    srcs = ["src/lib.rs"],
)

rust_test(
    name = "unionfind_test",
    size = "small",
    crate = ":unionfind",
)
