fc_data_dir: /data/testbed

packages:
  - cpio
  - curl
  - e2fsprogs
  - iproute2
  - nftables
  - openbsd-netcat
  - squashfs-tools

cpu_vendor: intel
cpu_arch: x86_64

vext_host_forward: true

vext_ext_ip: 192.168.200.1
vext_int_ip: 192.168.200.2
vext_prefix: 24
