load("//bazel:rust.bzl", "rust")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust.library(
    name = "protoc_plugin",
    srcs = ["src/lib.rs"],
    deps = [
        "@crates//:anyhow",
        "@crates//:prost",
        "@crates//:prost-reflect",
        "@crates//:prost-types",
    ],
)
