load("@rules_rust//rust:defs.bzl", "rust_library")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

rust_library(
    name = "protoc_plugin",
    srcs = ["src/lib.rs"],
    deps = [
        "@crates//:anyhow",
        "@crates//:prost",
        "@crates//:prost-reflect",
        "@crates//:prost-types",
    ],
)
