"all":
  "hosts":
    "node_a":
      "ansible_host": "node_a"
      "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o ProxyCommand='sudo
        ip netns exec node_a nc 172.16.0.1 %p'"
      "bridge_ipv4": "10.0.0.1"
      "bridge_ipv6": "fd10::1"
      "fc_ipv6": "fdfc:a::1"
      "fc_peers":
      - "fdfc:b::1"
      "node_name": "node_a"
      "tap_ipv4": "172.16.0.0"
      "tap_ipv6": "fdfc:a::0"
      "tap_prefix6": 127
