load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test", "rust_test_suite")

rust_library(
    name = "bitfunnel",
    srcs = [
        "src/lib.rs",
        "src/signatures.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//syx/bitcomp_roaring",
    ],
)

rust_test(
    name = "bitfunnel_test",
    size = "small",
    crate = ":bitfunnel",
)

rust_test_suite(
    name = "bitfunnel_test_suite",
    size = "small",
    srcs = ["tests/signatures.rs"],
    deps = [
        ":bitfunnel",
        "@crates//:rand",
    ],
)
