- name: Ensure IPv4 forwarding is enabled
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Ensure IPv6 forwarding is enabled
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: true
    state: present
    reload: true
