- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Check if bridge exists
      register: bridge_check
      failed_when: false
      changed_when: false
      ansible.builtin.command:
        cmd: ip link show {{ bridge_name }}

    - name: Remove bridge
      when: bridge_check.rc == 0
      ansible.builtin.command:
        cmd: ip link del {{ bridge_name }}
