"bridge_ipv4": "10.0.0.1"
"bridge_ipv6": "fd10::1"
"bridge_name": "br-fc"
"bridge_prefix4": 24
"bridge_prefix6": 64
"cpu_arch": "x86_64"
"cpu_vendor": "intel"
"fc_data_dir": "/data/firecracker"
"firecracker_version": "1.16.0"
"rootfs_filename": "rootfs.ext4"
"rootfs_squashfs_url": "https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/20260617-a093a70f7979-0/x86_64/ubuntu-24.04.squashfs"
"ssh_public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC5pxoNOgWpnc4nWGjDXVhZ8hXUNv91TnWdACqesqUYU
  testkey"
"vmlinux_url": "https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/20260617-a093a70f7979-0/x86_64/vmlinux-6.1.174"
