//! A protoc plugin emitting Arrow schemas, one Rust function per
//! message and one file per proto. A Parquet writer derives its own
//! schema from the Arrow one.
//!
//! A column is nullable exactly when its field has proto presence.

use prost_reflect::{
    FieldDescriptor,
    FileDescriptor,
    Kind,
    MessageDescriptor,
};
use prost_types::compiler::code_generator_response::File;

fn main() -> anyhow::Result<()> {
    protoc_plugin::gen_code(ArrowSchema::default())
}

#[derive(Debug, Default, Clone)]
struct ArrowSchema {}

impl protoc_plugin::GenFile for ArrowSchema {
    fn gen_file(&self, target_proto: &str, fd: &FileDescriptor) -> Result<File, String> {
        gen_file(target_proto, fd).map_err(|err| err.to_string())
    }
}

/// What stops a proto from having an Arrow schema. Each case names a
/// shape Arrow cannot hold, so the message says what to change.
#[derive(Debug, thiserror::Error)]
enum Error {
    #[error("unexpected proto '{0}', which does not end in .proto")]
    NotAProto(String),

    #[error(
        "'{0}' is recursive, and an Arrow schema is a finite tree. Hold it as bytes, or split \
         the recursion into a table of its own."
    )]
    Recursive(String),

    #[error(
        "'{0}' has no fields, and Parquet has no empty group. Give it a field, or hold its \
         presence as a bool."
    )]
    NoFields(String),

    #[error("map field '{0}' is not a message")]
    MalformedMap(String),
}

fn gen_file(target_proto: &str, fd: &FileDescriptor) -> Result<File, Error> {
    // protoc matches this name against the `outputs` the plugin target
    // declares, so the stem here and `{protopath}` there are the same
    // string. A mismatch is rejected with no output written.
    let stem = target_proto
        .strip_suffix(".proto")
        .ok_or_else(|| Error::NotAProto(target_proto.to_owned()))?;

    // Nested messages come out before the messages holding them, but
    // every schema is a free function, so declaration order is free.
    let mut body = String::with_capacity(1 << 12);
    for msg in all_messages(fd) {
        body.push('\n');
        body.push_str(&gen_schema(&msg, fd.package_name())?);
    }

    // Every type is named by absolute path and nothing is imported, so a
    // generated file cannot collide with the names where it is included,
    // and has no import that could go unused.
    //
    // The file is a crate root, so its doc is `//!`, which clippy holds
    // to the same `missing_docs` it holds the rest to.
    let mut buf = String::with_capacity(body.len() + (1 << 8));
    buf.push_str(&format!(
        "//! Arrow schemas for the messages in `{}`.\n//!\n\
         //! @generated by gen_arrow_schema. Do not edit.\n",
        target_proto,
    ));
    buf.push_str(&body);

    Ok(File {
        name: Some(format!("{}.arrow_schema.rs", stem)),
        content: Some(buf),
        ..Default::default()
    })
}

/// Every message the file declares, nested ones included. Map entries are
/// synthetic and become [`DataType::Map`] at their use site, so they are
/// not schemas of their own.
fn all_messages(fd: &FileDescriptor) -> Vec<MessageDescriptor> {
    fn walk(msg: MessageDescriptor, out: &mut Vec<MessageDescriptor>) {
        if msg.is_map_entry() {
            return;
        }
        for child in msg.child_messages() {
            walk(child, out);
        }
        out.push(msg);
    }

    let mut out = Vec::new();
    for msg in fd.messages() {
        walk(msg, &mut out);
    }
    out
}

fn gen_schema(msg: &MessageDescriptor, package: &str) -> Result<String, Error> {
    let fields = fields_expr(msg, &mut vec![msg.full_name().to_owned()], 2)?;

    Ok(format!(
        "/// Arrow schema for `{}`.\npub fn {}() -> ::arrow_schema::Schema {{\n    ::arrow_schema::Schema::new(vec![\n{}\n    ])\n}}\n",
        msg.full_name(),
        fn_name(msg, package),
        fields,
    ))
}

/// A column's Arrow type, and the canonical extension naming what its
/// bytes mean when the type alone does not say.
struct Column {
    data_type: String,
    extension: Option<&'static str>,
}

impl Column {
    fn plain(data_type: impl Into<String>) -> Self {
        Self { data_type: data_type.into(), extension: None }
    }

    /// `Empty` has no fields, so nothing to carry but whether the field
    /// was set. Nullability already carries that, and the bool is
    /// somewhere for it to sit.
    fn empty() -> Self {
        Self::plain("::arrow_schema::DataType::Boolean")
    }

    /// A proto timestamp is seconds and nanos since the Unix epoch, so
    /// nanoseconds lose nothing and the zone is not a guess.
    fn timestamp() -> Self {
        Self::plain(
            "::arrow_schema::DataType::Timestamp(\
             ::arrow_schema::TimeUnit::Nanosecond, Some(\"UTC\".into()))",
        )
    }

    /// A proto duration is seconds and nanos as well.
    fn duration() -> Self {
        Self::plain("::arrow_schema::DataType::Duration(::arrow_schema::TimeUnit::Nanosecond)")
    }

    /// Text holding JSON. The extension fixes the storage type to a
    /// string, so there is nothing for a caller to choose.
    fn json() -> Self {
        Self {
            data_type: "::arrow_schema::DataType::Utf8".to_owned(),
            extension: Some("::arrow_schema::extension::Json::default()"),
        }
    }
}

fn field_expr(name: &str, column: &Column, nullable: bool) -> String {
    let field =
        format!("::arrow_schema::Field::new(\"{}\", {}, {})", name, column.data_type, nullable,);
    match column.extension {
        None => field,
        Some(extension) => format!("{field}.with_extension_type({extension})"),
    }
}

/// A message's fields as a comma-separated list of `Field::new` calls.
///
/// `stack` carries the messages currently being expanded, so a message
/// reaching itself can be rejected: an Arrow schema is a finite tree and
/// cannot hold a cycle.
fn fields_expr(
    msg: &MessageDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let pad = "    ".repeat(depth);
    let mut out = Vec::with_capacity(msg.fields().len());

    for field in msg.fields() {
        // Nullability is proto presence. An implicit-presence scalar
        // always has a value, so it is not null; a message field, an
        // `optional` one, and a oneof arm can be absent, so it is.
        //
        // A oneof therefore needs no shape of its own. Its arms are
        // already plain fields here, and at most one is non-null, so
        // which arm was set reads off the nulls without a discriminant.
        let nullable = field.supports_presence();

        let expr = if field.is_map() {
            map_field(&field, nullable, stack, depth)?
        } else {
            field_expr(field.name(), &field_type(&field, stack, depth)?, nullable)
        };
        out.push(format!("{}{},", pad, expr));
    }

    Ok(out.join("\n"))
}

/// A proto map is a repeated entry of key and value, which is what Arrow
/// means by [`DataType::Map`]. `Field::new_map` builds the whole field,
/// including the rule that the entries group is never null.
fn map_field(
    field: &FieldDescriptor,
    nullable: bool,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let Kind::Message(entry) = field.kind() else {
        return Err(Error::MalformedMap(field.full_name().to_owned()));
    };
    let key = entry.map_entry_key_field();
    let value = entry.map_entry_value_field();

    let key_expr = field_expr("key", &kind_type(&key, stack, depth + 1)?, false);
    let value_expr =
        field_expr("value", &kind_type(&value, stack, depth + 1)?, value.supports_presence());
    let pad = "    ".repeat(depth + 1);
    let close = "    ".repeat(depth);

    Ok(format!(
        "::arrow_schema::Field::new_map(\n\
         {pad}\"{name}\",\n\
         {pad}\"entries\",\n\
         {pad}{key_expr},\n\
         {pad}{value_expr},\n\
         {pad}false,\n\
         {pad}{nullable},\n\
         {close})",
        name = field.name(),
    ))
}

fn field_type(
    field: &FieldDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<Column, Error> {
    let inner = kind_type(field, stack, depth + 1)?;
    if !field.is_list() {
        return Ok(inner);
    }

    // A repeated field is never absent, only empty, and none of its
    // elements is ever null. The element is named `item`, which is what
    // Parquet's three-level list encoding expects, and it is the element
    // rather than the list that carries any extension.
    Ok(Column::plain(match inner.extension {
        None => format!("::arrow_schema::DataType::new_list({}, false)", inner.data_type),
        Some(_) => format!(
            "::arrow_schema::DataType::List(::std::sync::Arc::new({}))",
            field_expr("item", &inner, false),
        ),
    }))
}

fn kind_type(
    field: &FieldDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<Column, Error> {
    let ty = match field.kind() {
        Kind::Double => "::arrow_schema::DataType::Float64",
        Kind::Float => "::arrow_schema::DataType::Float32",
        Kind::Int32 | Kind::Sint32 | Kind::Sfixed32 => "::arrow_schema::DataType::Int32",
        Kind::Int64 | Kind::Sint64 | Kind::Sfixed64 => "::arrow_schema::DataType::Int64",
        Kind::Uint32 | Kind::Fixed32 => "::arrow_schema::DataType::UInt32",
        Kind::Uint64 | Kind::Fixed64 => "::arrow_schema::DataType::UInt64",
        Kind::Bool => "::arrow_schema::DataType::Boolean",
        Kind::String => "::arrow_schema::DataType::Utf8",
        Kind::Bytes => "::arrow_schema::DataType::Binary",
        // A proto enum's number is its canonical form. Names move when a
        // constant is renamed; numbers are what the wire carries.
        Kind::Enum(_) => "::arrow_schema::DataType::Int32",
        Kind::Message(msg) => return message_type(&msg, stack, depth),
    };
    Ok(Column::plain(ty))
}

fn message_type(
    msg: &MessageDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<Column, Error> {
    if let Some(column) = well_known(msg.full_name()) {
        return Ok(column);
    }

    if stack.iter().any(|name| name == msg.full_name()) {
        return Err(Error::Recursive(msg.full_name().to_owned()));
    }

    if msg.fields().len() == 0 {
        return Err(Error::NoFields(msg.full_name().to_owned()));
    }

    stack.push(msg.full_name().to_owned());
    let fields = fields_expr(msg, stack, depth + 1);
    stack.pop();

    let close = "    ".repeat(depth);
    Ok(Column::plain(format!(
        "::arrow_schema::DataType::Struct(::arrow_schema::Fields::from(vec![\n{}\n{}]))",
        fields?, close
    )))
}

/// Well-known types Arrow spells natively, plus `Empty` and `Struct`,
/// which the generic path cannot reach at all: the first has no fields
/// and so no group Parquet accepts, and the second reaches itself
/// through `Value` and so is no finite tree.
///
/// `Any` is absent on purpose. It is an ordinary message of `type_url`
/// and `value`, so expanding it like any other gives the same two
/// columns, opaque payload included.
fn well_known(full_name: &str) -> Option<Column> {
    Some(match full_name {
        "google.protobuf.Empty" => Column::empty(),
        "google.protobuf.Struct" | "google.protobuf.ListValue" | "google.protobuf.Value" => {
            Column::json()
        }
        "google.protobuf.Timestamp" => Column::timestamp(),
        "google.protobuf.Duration" => Column::duration(),
        "google.protobuf.BoolValue" => Column::plain("::arrow_schema::DataType::Boolean"),
        "google.protobuf.StringValue" => Column::plain("::arrow_schema::DataType::Utf8"),
        "google.protobuf.BytesValue" => Column::plain("::arrow_schema::DataType::Binary"),
        "google.protobuf.Int32Value" => Column::plain("::arrow_schema::DataType::Int32"),
        "google.protobuf.Int64Value" => Column::plain("::arrow_schema::DataType::Int64"),
        "google.protobuf.UInt32Value" => Column::plain("::arrow_schema::DataType::UInt32"),
        "google.protobuf.UInt64Value" => Column::plain("::arrow_schema::DataType::UInt64"),
        "google.protobuf.FloatValue" => Column::plain("::arrow_schema::DataType::Float32"),
        "google.protobuf.DoubleValue" => Column::plain("::arrow_schema::DataType::Float64"),
        _ => return None,
    })
}

/// A message's schema function, named by its path below the file's
/// package: `Customer.Id.Email` becomes `customer_id_email`.
fn fn_name(msg: &MessageDescriptor, package: &str) -> String {
    let path = msg.full_name().strip_prefix(package).unwrap_or(msg.full_name());
    let path = path.trim_start_matches('.');

    let mut out = String::with_capacity(path.len() + 8);
    for (i, ch) in path.char_indices() {
        match ch {
            '.' => out.push('_'),
            c if c.is_ascii_uppercase() => {
                if i > 0 && !out.ends_with('_') {
                    out.push('_');
                }
                out.push(c.to_ascii_lowercase());
            }
            c => out.push(c),
        }
    }
    out
}
