//! A protoc plugin emitting Arrow schemas, one Rust function per
//! message and one file per proto. A Parquet writer derives its own
//! schema from the Arrow one.
//!
//! A column is nullable exactly when its field has proto presence.

use heck::ToSnakeCase;
use protobuf::plugin::code_generator_response::File;
use protobuf::reflect::{
    FieldDescriptor,
    FileDescriptor,
    MessageDescriptor,
    RuntimeFieldType,
    RuntimeType,
    Syntax,
};

fn main() -> anyhow::Result<()> {
    protoc_plugin::run(ArrowSchema::default())
}

#[derive(Debug, Default, Clone)]
struct ArrowSchema {}

impl protoc_plugin::GenFile for ArrowSchema {
    fn gen_file(&self, target_proto: &str, fd: &FileDescriptor) -> Result<File, String> {
        gen_file(target_proto, fd).map_err(|err| err.to_string())
    }
}

/// What stops a proto from having an Arrow schema. Each case names a
/// shape Arrow cannot hold, so the message says what to change.
#[derive(Debug, thiserror::Error)]
enum Error {
    #[error("unexpected proto '{0}', which does not end in .proto")]
    NotAProto(String),

    #[error(
        "'{0}' is recursive, and an Arrow schema is a finite tree. Hold it as bytes, or split \
         the recursion into a table of its own."
    )]
    Recursive(String),

    #[error(
        "'{0}' has no fields, and Parquet has no empty group. Give it a field, or hold its \
         presence as a bool."
    )]
    NoFields(String),
}

fn gen_file(target_proto: &str, fd: &FileDescriptor) -> Result<File, Error> {
    // protoc matches this name against the `outputs` the plugin target
    // declares, so the stem here and `{protopath}` there are the same
    // string. A mismatch is rejected with no output written.
    let stem = target_proto
        .strip_suffix(".proto")
        .ok_or_else(|| Error::NotAProto(target_proto.to_owned()))?;

    // The header is `//!`: a generated file is used as a crate root.
    let mut buf = String::with_capacity(1 << 12);
    buf.push_str(&format!(
        "//! Arrow schemas for the messages in `{}`.\n//!\n\
         //! Generated by gen_arrow_schema. Do not edit.\n",
        target_proto,
    ));

    // Nested messages come out before the messages holding them, but
    // every schema is a free function, so declaration order is free.
    for msg in all_messages(fd) {
        buf.push('\n');
        buf.push_str(&gen_schema(&msg, fd.package())?);
    }

    Ok(File {
        name: Some(format!("{}.arrow_schema.rs", stem)),
        content: Some(buf),
        ..Default::default()
    })
}

/// Every message the file declares, nested ones included. Map entries are
/// synthetic and become [`DataType::Map`] at their use site, so they are
/// not schemas of their own.
fn all_messages(fd: &FileDescriptor) -> Vec<MessageDescriptor> {
    fn walk(msg: MessageDescriptor, out: &mut Vec<MessageDescriptor>) {
        if msg.is_map_entry() {
            return;
        }
        for child in msg.nested_messages() {
            walk(child, out);
        }
        out.push(msg);
    }

    let mut out = Vec::new();
    for msg in fd.messages() {
        walk(msg, &mut out);
    }
    out
}

fn gen_schema(msg: &MessageDescriptor, package: &str) -> Result<String, Error> {
    // One source line per emitted line, so the indentation of the
    // generated code is the indentation written here.
    Ok(format!(
        concat!(
            "/// Arrow schema for `{full_name}`.\n",
            "pub fn {fn_name}() -> ::arrow_schema::Schema {{\n",
            "    ::arrow_schema::Schema::new(vec![\n",
            "{fields}\n",
            "    ])\n",
            "}}\n",
        ),
        full_name = msg.full_name(),
        fn_name = fn_name(msg, package),
        fields = field_exprs(msg, &Expanding::root(msg))?
            .iter()
            .map(|field| format!("        {field},"))
            .collect::<Vec<_>>()
            .join("\n"),
    ))
}

/// A column's Arrow type, and the canonical extension naming what its
/// bytes mean when the type alone does not say.
struct Column {
    data_type: String,
    extension: Option<&'static str>,
}

impl Column {
    fn plain(data_type: impl Into<String>) -> Self {
        Self { data_type: data_type.into(), extension: None }
    }

    /// `Empty` has no fields, so nothing to carry but whether the field
    /// was set. Nullability already carries that, and the bool is
    /// somewhere for it to sit.
    fn empty() -> Self {
        Self::plain("::arrow_schema::DataType::Boolean")
    }

    /// A proto timestamp is seconds and nanos since the Unix epoch, so
    /// nanoseconds lose nothing and the zone is not a guess.
    fn timestamp() -> Self {
        Self::plain(
            "::arrow_schema::DataType::Timestamp(\
             ::arrow_schema::TimeUnit::Nanosecond, Some(\"UTC\".into()))",
        )
    }

    /// A proto duration is seconds and nanos as well.
    fn duration() -> Self {
        Self::plain("::arrow_schema::DataType::Duration(::arrow_schema::TimeUnit::Nanosecond)")
    }

    /// Text holding JSON. The extension fixes the storage type to a
    /// string, so there is nothing for a caller to choose.
    fn json() -> Self {
        Self {
            data_type: "::arrow_schema::DataType::Utf8".to_owned(),
            extension: Some("::arrow_schema::extension::Json::default()"),
        }
    }
}

/// Whether a field distinguishes "unset" from its default value.
fn supports_presence(field: &FieldDescriptor) -> bool {
    // A oneof arm and a proto3 `optional` field are the same case:
    // `optional` is a synthetic oneof of one arm.
    if field.containing_oneof_including_synthetic().is_some() {
        return true;
    }

    match field.runtime_field_type() {
        // A message has no zero value that an unset field could be read
        // as, so a message field has presence under either syntax.
        RuntimeFieldType::Singular(RuntimeType::Message(_msg)) => true,
        // An implicit-presence proto3 scalar always carries a value, so
        // only proto2 leaves a bare scalar somewhere to be absent from.
        RuntimeFieldType::Singular(_scalar) => {
            field.containing_message().file_descriptor().syntax() == Syntax::Proto2
        }
        // A repeated field and a map have no unset state to report, only
        // an empty one.
        RuntimeFieldType::Repeated(_item) => false,
        RuntimeFieldType::Map(_k, _v) => false,
    }
}

fn field_expr(name: &str, column: &Column, nullable: bool) -> String {
    let field =
        format!("::arrow_schema::Field::new(\"{}\", {}, {})", name, column.data_type, nullable,);
    match column.extension {
        None => field,
        Some(extension) => format!("{field}.with_extension_type({extension})"),
    }
}

/// Catches a message that reaches itself: the path from the
/// message being expanded outward to the root.
///
/// A path, not a record of every message expanded so far: so two
/// separate fields reaching the same message each expand it, and
/// only a message found on its own path is a cycle.
struct Expanding<'a> {
    desc:  &'a MessageDescriptor,
    outer: Option<&'a Expanding<'a>>,
}

impl<'a> Expanding<'a> {
    /// The outermost message of a schema.
    fn root(desc: &'a MessageDescriptor) -> Self {
        Self { desc, outer: None }
    }

    /// This chain with `desc` on the end, to be bound for
    /// as long as `desc` is being expanded.
    fn enter<'outer, 'inner>(&'outer self, desc: &'inner MessageDescriptor) -> Expanding<'inner>
    where
        'outer: 'inner,
    {
        Expanding { desc, outer: Some(self) }
    }

    /// Whether `msg` is on the path out to the root, which makes
    /// expanding it again a cycle.
    ///
    /// Comparing full names is comparing identity: protoc refuses a
    /// compilation in which two messages share one, and a request
    /// carries a single compilation, imports included.
    fn on_path(&self, desc: &MessageDescriptor) -> bool {
        self.desc.full_name() == desc.full_name()
            || self.outer.is_some_and(|outer| outer.on_path(desc))
    }
}

/// A message's fields, each a `Field::new` call. Nothing here wraps or
/// indents: the caller joins them however it likes, and the whole file
/// is generated code that a formatter can lay out afterwards.
fn field_exprs(msg: &MessageDescriptor, expanding: &Expanding) -> Result<Vec<String>, Error> {
    let mut out = Vec::new();

    for field in msg.fields() {
        // A oneof needs no Arrow type of its own: `fields()` hands back
        // its arms as plain nullable fields, at most one of which is
        // ever set, so the non-null column is the arm that was chosen
        // and no tag column has to carry it.
        let nullable = supports_presence(&field);

        out.push(match field.runtime_field_type() {
            RuntimeFieldType::Map(key, val) => map_field(&field, &key, &val, nullable, expanding)?,
            RuntimeFieldType::Repeated(item) => {
                field_expr(field.name(), &list_type(&item, expanding)?, nullable)
            }
            RuntimeFieldType::Singular(item) => {
                field_expr(field.name(), &runtime_type(&item, expanding)?, nullable)
            }
        });
    }

    Ok(out)
}

/// A proto map is a repeated entry of key and value, which is what Arrow
/// means by [`DataType::Map`]. `Field::new_map` builds the whole field,
/// including the rule that the entries group is never null.
fn map_field(
    field: &FieldDescriptor,
    key: &RuntimeType,
    val: &RuntimeType,
    nullable: bool,
    expanding: &Expanding,
) -> Result<String, Error> {
    // An entry's key is a scalar and always present. Its value has
    // presence exactly when it is a message.
    let key_expr = field_expr("key", &runtime_type(key, expanding)?, false);
    let value_expr = field_expr(
        "value",
        &runtime_type(val, expanding)?,
        matches!(val, RuntimeType::Message(_msg)),
    );

    Ok(format!(
        "::arrow_schema::Field::new_map(\"{name}\", \"entries\", {key_expr}, {value_expr}, \
         false, {nullable})",
        name = field.name(),
    ))
}

/// A repeated field is never absent, only empty, and none of its
/// elements is ever null. The element is named `item`, which is what
/// Parquet's three-level list encoding expects, and it is the element
/// rather than the list that carries any extension.
fn list_type(item: &RuntimeType, expanding: &Expanding) -> Result<Column, Error> {
    let inner = runtime_type(item, expanding)?;
    Ok(Column::plain(match inner.extension {
        None => format!("::arrow_schema::DataType::new_list({}, false)", inner.data_type),
        Some(_extension) => format!(
            "::arrow_schema::DataType::List(::std::sync::Arc::new({}))",
            field_expr("item", &inner, false),
        ),
    }))
}

fn runtime_type(ty: &RuntimeType, expanding: &Expanding) -> Result<Column, Error> {
    let data_type = match ty {
        RuntimeType::F64 => "::arrow_schema::DataType::Float64",
        RuntimeType::F32 => "::arrow_schema::DataType::Float32",
        RuntimeType::I32 => "::arrow_schema::DataType::Int32",
        RuntimeType::I64 => "::arrow_schema::DataType::Int64",
        RuntimeType::U32 => "::arrow_schema::DataType::UInt32",
        RuntimeType::U64 => "::arrow_schema::DataType::UInt64",
        RuntimeType::Bool => "::arrow_schema::DataType::Boolean",
        RuntimeType::String => "::arrow_schema::DataType::Utf8",
        RuntimeType::VecU8 => "::arrow_schema::DataType::Binary",
        // A proto enum's number is its canonical form. Names move when a
        // constant is renamed; numbers are what the wire carries.
        RuntimeType::Enum(_enum) => "::arrow_schema::DataType::Int32",
        RuntimeType::Message(msg) => return message_type(msg, expanding),
    };
    Ok(Column::plain(data_type))
}

fn message_type(msg: &MessageDescriptor, expanding: &Expanding) -> Result<Column, Error> {
    // Checked first: `Empty` and `Struct` would trip the rules below.
    if let Some(column) = well_known(msg.full_name()) {
        return Ok(column);
    }

    if expanding.on_path(msg) {
        return Err(Error::Recursive(msg.full_name().to_owned()));
    }

    if msg.fields().next().is_none() {
        return Err(Error::NoFields(msg.full_name().to_owned()));
    }

    let expanding = expanding.enter(msg);
    Ok(Column::plain(format!(
        "::arrow_schema::DataType::Struct(::arrow_schema::Fields::from(vec![{}]))",
        field_exprs(msg, &expanding)?.join(", "),
    )))
}

/// Well-known types Arrow spells natively, plus `Empty` and `Struct`,
/// which the generic path cannot reach at all: the first has no fields
/// and so no group Parquet accepts, and the second reaches itself
/// through `Value` and so is no finite tree.
///
/// `Any` is absent on purpose. It is an ordinary message of `type_url`
/// and `value`, so expanding it like any other gives the same two
/// columns, opaque payload included.
fn well_known(full_name: &str) -> Option<Column> {
    Some(match full_name {
        "google.protobuf.Empty" => Column::empty(),
        "google.protobuf.Struct" | "google.protobuf.ListValue" | "google.protobuf.Value" => {
            Column::json()
        }
        "google.protobuf.Timestamp" => Column::timestamp(),
        "google.protobuf.Duration" => Column::duration(),
        "google.protobuf.BoolValue" => Column::plain("::arrow_schema::DataType::Boolean"),
        "google.protobuf.StringValue" => Column::plain("::arrow_schema::DataType::Utf8"),
        "google.protobuf.BytesValue" => Column::plain("::arrow_schema::DataType::Binary"),
        "google.protobuf.Int32Value" => Column::plain("::arrow_schema::DataType::Int32"),
        "google.protobuf.Int64Value" => Column::plain("::arrow_schema::DataType::Int64"),
        "google.protobuf.UInt32Value" => Column::plain("::arrow_schema::DataType::UInt32"),
        "google.protobuf.UInt64Value" => Column::plain("::arrow_schema::DataType::UInt64"),
        "google.protobuf.FloatValue" => Column::plain("::arrow_schema::DataType::Float32"),
        "google.protobuf.DoubleValue" => Column::plain("::arrow_schema::DataType::Float64"),
        _ => return None,
    })
}

/// A message's schema function, named by its path below the file's
/// package: `Customer.Id.Email` becomes `customer_id_email`. A dot is a
/// word boundary to `to_snake_case`, so the leading one left by
/// stripping the package folds away with the rest.
fn fn_name(msg: &MessageDescriptor, package: &str) -> String {
    let path = msg.full_name().strip_prefix(package).unwrap_or(msg.full_name());
    path.to_snake_case()
}
