#![allow(missing_docs)]
use prost_reflect::{
    FieldDescriptor,
    FileDescriptor,
    Kind,
    MessageDescriptor,
};
use prost_types::compiler::code_generator_response::File;

fn main() -> anyhow::Result<()> {
    protoc_plugin::gen_code(ArrowSchema::default())
}

/// Generates Arrow schemas, which a Parquet writer derives its own schema
/// from, for every message in a proto file.
#[derive(Debug, Default, Clone)]
struct ArrowSchema {}

impl protoc_plugin::GenFile for ArrowSchema {
    fn gen_file(&self, target_proto: &str, fd: &FileDescriptor) -> Result<File, String> {
        gen_file(target_proto, fd).map_err(|err| err.to_string())
    }
}

/// What stops a proto from having an Arrow schema. Each case names a
/// shape Arrow cannot hold, so the message says what to change.
#[derive(Debug, thiserror::Error)]
enum Error {
    #[error("unexpected proto '{0}', which does not end in .proto")]
    NotAProto(String),

    #[error(
        "'{0}' is recursive, and an Arrow schema is a finite tree. Hold it as bytes, or split \
         the recursion into a table of its own."
    )]
    Recursive(String),

    #[error(
        "'{0}' has no fields, and Parquet has no empty group. Give it a field, or hold its \
         presence as a bool."
    )]
    NoFields(String),

    #[error("map field '{0}' is not a message")]
    MalformedMap(String),
}

fn gen_file(target_proto: &str, fd: &FileDescriptor) -> Result<File, Error> {
    // protoc matches this name against the `outputs` the plugin target
    // declares, so the stem here and `{protopath}` there are the same
    // string. A mismatch is rejected with no output written.
    let stem = target_proto
        .strip_suffix(".proto")
        .ok_or_else(|| Error::NotAProto(target_proto.to_owned()))?;

    // Nested messages come out before the messages holding them, but
    // every schema is a free function, so declaration order is free.
    let mut body = String::with_capacity(1 << 12);
    for msg in all_messages(fd) {
        body.push('\n');
        body.push_str(&gen_schema(&msg, fd.package_name())?);
    }

    // Every type is named by absolute path and nothing is imported, so a
    // generated file cannot collide with the names where it is included,
    // and has no import that could go unused.
    //
    // The file is a crate root, so its doc is `//!`, which clippy holds
    // to the same `missing_docs` it holds the rest to.
    let mut buf = String::with_capacity(body.len() + (1 << 8));
    buf.push_str(&format!(
        "//! Arrow schemas for the messages in `{}`.\n//!\n\
         //! @generated by gen_arrow_schema. Do not edit.\n",
        target_proto,
    ));
    buf.push_str(&body);

    Ok(File {
        name: Some(format!("{}.arrow_schema.rs", stem)),
        content: Some(buf),
        ..Default::default()
    })
}

/// Every message the file declares, nested ones included. Map entries are
/// synthetic and become [`DataType::Map`] at their use site, so they are
/// not schemas of their own.
fn all_messages(fd: &FileDescriptor) -> Vec<MessageDescriptor> {
    fn walk(msg: MessageDescriptor, out: &mut Vec<MessageDescriptor>) {
        if msg.is_map_entry() {
            return;
        }
        for child in msg.child_messages() {
            walk(child, out);
        }
        out.push(msg);
    }

    let mut out = Vec::new();
    for msg in fd.messages() {
        walk(msg, &mut out);
    }
    out
}

fn gen_schema(msg: &MessageDescriptor, package: &str) -> Result<String, Error> {
    let fields = fields_expr(msg, &mut vec![msg.full_name().to_owned()], 2)?;

    Ok(format!(
        "/// Arrow schema for `{}`.\npub fn {}() -> ::arrow::datatypes::Schema {{\n    ::arrow::datatypes::Schema::new(vec![\n{}\n    ])\n}}\n",
        msg.full_name(),
        fn_name(msg, package),
        fields,
    ))
}

/// A message's fields as a comma-separated list of `Field::new` calls.
///
/// `stack` carries the messages currently being expanded, so a message
/// reaching itself can be rejected: an Arrow schema is a finite tree and
/// cannot hold a cycle.
fn fields_expr(
    msg: &MessageDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let pad = "    ".repeat(depth);
    let mut out = Vec::with_capacity(msg.fields().len());

    for field in msg.fields() {
        // Nullability is proto presence. An implicit-presence scalar
        // always has a value, so it is not null; a message field, an
        // `optional` one, and a oneof arm can be absent, so it is.
        //
        // A oneof therefore needs no shape of its own. Its arms are
        // already plain fields here, and at most one is non-null, so
        // which arm was set reads off the nulls without a discriminant.
        let nullable = field.supports_presence();

        let expr = if field.is_map() {
            map_field(&field, nullable, stack, depth)?
        } else {
            format!(
                "::arrow::datatypes::Field::new(\"{}\", {}, {})",
                field.name(),
                field_type(&field, stack, depth)?,
                nullable,
            )
        };
        out.push(format!("{}{},", pad, expr));
    }

    Ok(out.join("\n"))
}

/// A proto map is a repeated entry of key and value, which is what Arrow
/// means by [`DataType::Map`]. `Field::new_map` builds the whole field,
/// including the rule that the entries group is never null.
fn map_field(
    field: &FieldDescriptor,
    nullable: bool,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let Kind::Message(entry) = field.kind() else {
        return Err(Error::MalformedMap(field.full_name().to_owned()));
    };
    let key = entry.map_entry_key_field();
    let value = entry.map_entry_value_field();

    let key_ty = kind_type(&key, stack, depth + 1)?;
    let value_ty = kind_type(&value, stack, depth + 1)?;
    let pad = "    ".repeat(depth + 1);
    let close = "    ".repeat(depth);

    Ok(format!(
        "::arrow::datatypes::Field::new_map(\n\
         {pad}\"{name}\",\n\
         {pad}\"entries\",\n\
         {pad}::arrow::datatypes::Field::new(\"key\", {key_ty}, false),\n\
         {pad}::arrow::datatypes::Field::new(\"value\", {value_ty}, {value_null}),\n\
         {pad}false,\n\
         {pad}{nullable},\n\
         {close})",
        name = field.name(),
        value_null = value.supports_presence(),
    ))
}

fn field_type(
    field: &FieldDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let inner = kind_type(field, stack, depth + 1)?;

    // A repeated field is never absent, only empty, and none of its
    // elements is ever null. `new_list` names the element `item`, which
    // is what Parquet's three-level list encoding expects.
    if field.is_list() {
        return Ok(format!("::arrow::datatypes::DataType::new_list({}, false)", inner));
    }
    Ok(inner)
}

fn kind_type(
    field: &FieldDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    let ty = match field.kind() {
        Kind::Double => "::arrow::datatypes::DataType::Float64".to_owned(),
        Kind::Float => "::arrow::datatypes::DataType::Float32".to_owned(),
        Kind::Int32 | Kind::Sint32 | Kind::Sfixed32 => {
            "::arrow::datatypes::DataType::Int32".to_owned()
        }
        Kind::Int64 | Kind::Sint64 | Kind::Sfixed64 => {
            "::arrow::datatypes::DataType::Int64".to_owned()
        }
        Kind::Uint32 | Kind::Fixed32 => "::arrow::datatypes::DataType::UInt32".to_owned(),
        Kind::Uint64 | Kind::Fixed64 => "::arrow::datatypes::DataType::UInt64".to_owned(),
        Kind::Bool => "::arrow::datatypes::DataType::Boolean".to_owned(),
        Kind::String => "::arrow::datatypes::DataType::Utf8".to_owned(),
        Kind::Bytes => "::arrow::datatypes::DataType::Binary".to_owned(),
        // A proto enum's number is its canonical form. Names move when a
        // constant is renamed; numbers are what the wire carries.
        Kind::Enum(_) => "::arrow::datatypes::DataType::Int32".to_owned(),
        Kind::Message(msg) => message_type(&msg, stack, depth)?,
    };
    Ok(ty)
}

fn message_type(
    msg: &MessageDescriptor,
    stack: &mut Vec<String>,
    depth: usize,
) -> Result<String, Error> {
    if let Some(ty) = well_known(msg.full_name()) {
        return Ok(ty.to_owned());
    }

    if stack.iter().any(|name| name == msg.full_name()) {
        return Err(Error::Recursive(msg.full_name().to_owned()));
    }

    if msg.fields().len() == 0 {
        return Err(Error::NoFields(msg.full_name().to_owned()));
    }

    stack.push(msg.full_name().to_owned());
    let fields = fields_expr(msg, stack, depth + 1);
    stack.pop();

    let close = "    ".repeat(depth);
    Ok(format!(
        "::arrow::datatypes::DataType::Struct(::arrow::datatypes::Fields::from(vec![\n{}\n{}]))",
        fields?, close
    ))
}

/// Well-known types Arrow has a native spelling for, plus the two that
/// have no shape of their own: `Any` carries an opaque payload, and
/// `Empty` would be a group with no children.
fn well_known(full_name: &str) -> Option<&'static str> {
    Some(match full_name {
        "google.protobuf.Timestamp" => {
            "::arrow::datatypes::DataType::Timestamp(::arrow::datatypes::TimeUnit::Nanosecond, Some(\"UTC\".into()))"
        }
        "google.protobuf.Duration" => {
            "::arrow::datatypes::DataType::Duration(::arrow::datatypes::TimeUnit::Nanosecond)"
        }
        "google.protobuf.Empty" => "::arrow::datatypes::DataType::Boolean",
        "google.protobuf.Any" => {
            "::arrow::datatypes::DataType::Struct(::arrow::datatypes::Fields::from(vec![\
             ::arrow::datatypes::Field::new(\"type_url\", ::arrow::datatypes::DataType::Utf8, false), \
             ::arrow::datatypes::Field::new(\"value\", ::arrow::datatypes::DataType::Binary, false)]))"
        }
        "google.protobuf.BoolValue" => "::arrow::datatypes::DataType::Boolean",
        "google.protobuf.StringValue" => "::arrow::datatypes::DataType::Utf8",
        "google.protobuf.BytesValue" => "::arrow::datatypes::DataType::Binary",
        "google.protobuf.Int32Value" => "::arrow::datatypes::DataType::Int32",
        "google.protobuf.Int64Value" => "::arrow::datatypes::DataType::Int64",
        "google.protobuf.UInt32Value" => "::arrow::datatypes::DataType::UInt32",
        "google.protobuf.UInt64Value" => "::arrow::datatypes::DataType::UInt64",
        "google.protobuf.FloatValue" => "::arrow::datatypes::DataType::Float32",
        "google.protobuf.DoubleValue" => "::arrow::datatypes::DataType::Float64",
        _ => return None,
    })
}

/// A message's schema function, named by its path below the file's
/// package: `Customer.Id.Email` becomes `customer_id_email`.
fn fn_name(msg: &MessageDescriptor, package: &str) -> String {
    let path = msg.full_name().strip_prefix(package).unwrap_or(msg.full_name());
    let path = path.trim_start_matches('.');

    let mut out = String::with_capacity(path.len() + 8);
    for (i, ch) in path.char_indices() {
        match ch {
            '.' => out.push('_'),
            c if c.is_ascii_uppercase() => {
                if i > 0 && !out.ends_with('_') {
                    out.push('_');
                }
                out.push(c.to_ascii_lowercase());
            }
            c => out.push(c),
        }
    }
    out
}
