name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Allow reading contents.

jobs:
  testing:
    name: Testing

    strategy:
      matrix:
        os:
          - ubuntu-latest
        profile:
          - release

    runs-on: ${{ matrix.os }}

    env:
      # Always use colored output.
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # https://github.com/nixbuild/nix-quick-install-action/blob/master/action.yml
      - name: Setup nix without nix-daemon
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            keep-outputs = true
            keep-env-derivations = true

      - name: Restore nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          # restore and save a cache using this key.
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix.
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # perform gc until the nix store size (in bytes) is at most this number
          # before trying to save a new cache.
          gc-max-store-size-linux: 2G

      - name: Show nix flake
        run: nix flake show

      - name: Restore prek cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ~/.cache/prek
          key: prek-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Restore bazel cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: restore-bazel-cache
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ matrix.os }}-${{ env.cache-name }}-

      - name: Restore rust cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          # A format string used to format commands to be run, i.e. `rustc` and `cargo`.
          cmd-format: nix develop --command {0}
          # The prefix cache key, this can be changed to start a new cache manually.
          prefix-key: "rust-cache-v0"
          # If `true` the workspace crates will be cached.
          # Useful if the workspace contains libraries that are only updated sporadically.
          cache-workspace-crates: "true"
          # To only cache release builds from `main`.
          save-if: ${{ github.ref == 'refs/heads/main' && matrix.profile == 'release' }}

      - name: Run prek
        run: nix develop --command prek run --skip no-commit-to-branch --show-diff-on-failure --color=always

      - name: Run cargo fmt
        run: nix develop --command cargo fmt --all --check

      - name: Run cargo check
        run: nix develop --command cargo check --locked

      - name: Run cargo clippy
        run: nix develop --command cargo clippy --locked --no-deps --all-targets --all-features

      - name: Run cargo build
        run: nix develop --command cargo build --locked --profile "${{ matrix.profile }}" --workspace

      - name: Run cargo test
        run: nix develop --command cargo test --locked --profile "${{ matrix.profile }}" --workspace

      - name: Run bazel build
        run: nix develop --command bazel build --config=ci //...

      - name: Run bazel test
        run: nix develop --command bazel test --config=ci //...

      - name: Save bazel cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        if: github.ref == 'refs/heads/main'
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ steps.restore-bazel-cache.outputs.cache-primary-key }}
